---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ0ZXN0LmNvbSI6eyJ1c2VybmFtZSI6ImZvbyIsInBhc3N3b3JkIjoiYmFyIiwiYXV0aCI6IlptOXZPbUpoY2c9PSJ9fX0=
kind: Secret
metadata:
  name: regcred
  namespace: test
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ0ZXN0LmNvbSI6eyJ1c2VybmFtZSI6ImZvbyIsInBhc3N3b3JkIjoiYmFyIiwiYXV0aCI6IlptOXZPbUpoY2c9PSJ9fX0=
kind: Secret
metadata:
  name: regcred-unused
  namespace: test
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  foo: YmFy
kind: Secret
metadata:
  name: test
  namespace: test
---
apiVersion: v1
data:
  foo: YmFy
kind: Secret
metadata:
  name: test-statefulset
  namespace: test
---
apiVersion: v1
data:
  foo: YmFy
kind: Secret
metadata:
  name: test-unused
  namespace: test