---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test
  namespace: test
  labels:
    app: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: busybox
        name: one
        command: ["sleep"]
        args: ["infinity"]
        envFrom:
        - secretRef:
            name: test
      - image: busybox
        name: two
        command: ["sleep"]
        args: ["infinity"]
        env:
        - name: test
          valueFrom:
            secretKeyRef:
              name: test
              key: foo
        volumeMounts:
        - name: foo
          mountPath: "/etc/secret"
          readOnly: true
      volumes:
      - name: foo
        secret:
          secretName: test