apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route
  namespace: nginx
spec:
  parentRefs:
  - name: gateway
    sectionName: http
    kind: Gateway
  hostnames:
  - <REDACTED>
  rules:
  - matches:
    - path: 
        type: PathPrefix
        value: /nginx
    filters:
      - type: URLRewrite
        urlRewrite:
          path:
            replacePrefixMatch: /
            type: ReplacePrefixMatch
    backendRefs:
    - name: nginx
      port: 80
